require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
Style/Documentation:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
AllCops:
  SuggestExtensions: false

RSpec/ExampleLength: 
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
  