require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
Style/Documentation:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
AllCops:
  SuggestExtensions: false

RSpec/ExampleLength: 
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Rails/BulkChangeTable:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
