# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/wroom_projects', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # WroomProject. As you add validations to WroomProject, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      WroomProject.create! valid_attributes
      get wroom_projects_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      wroom_project = WroomProject.create! valid_attributes
      get wroom_project_url(wroom_project)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_wroom_project_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      wroom_project = WroomProject.create! valid_attributes
      get edit_wroom_project_url(wroom_project)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new WroomProject' do
        expect do
          post wroom_projects_url, params: { wroom_project: valid_attributes }
        end.to change(WroomProject, :count).by(1)
      end

      it 'redirects to the created wroom_project' do
        post wroom_projects_url, params: { wroom_project: valid_attributes }
        expect(response).to redirect_to(wroom_project_url(WroomProject.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new WroomProject' do
        expect do
          post wroom_projects_url, params: { wroom_project: invalid_attributes }
        end.to change(WroomProject, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post wroom_projects_url, params: { wroom_project: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested wroom_project' do
        wroom_project = WroomProject.create! valid_attributes
        patch wroom_project_url(wroom_project), params: { wroom_project: new_attributes }
        wroom_project.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the wroom_project' do
        wroom_project = WroomProject.create! valid_attributes
        patch wroom_project_url(wroom_project), params: { wroom_project: new_attributes }
        wroom_project.reload
        expect(response).to redirect_to(wroom_project_url(wroom_project))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        wroom_project = WroomProject.create! valid_attributes
        patch wroom_project_url(wroom_project), params: { wroom_project: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested wroom_project' do
      wroom_project = WroomProject.create! valid_attributes
      expect do
        delete wroom_project_url(wroom_project)
      end.to change(WroomProject, :count).by(-1)
    end

    it 'redirects to the wroom_projects list' do
      wroom_project = WroomProject.create! valid_attributes
      delete wroom_project_url(wroom_project)
      expect(response).to redirect_to(wroom_projects_url)
    end
  end
end
